const DEFAULT_ENV_PLATFORM = 'node';
const DEFAULT_DATABASE_NAME = 'default';
const DEFAULT_DATABASE_EXTENSION = '.db';

module.exports = {
  DEFAULT_ENV_PLATFORM,
  DEFAULT_DATABASE_NAME,
  DEFAULT_DATABASE_EXTENSION,
};